### ISSUE TITLE
[1.15.2] Dedicated server Crash- Exception caught during firing event: null ... com.maciej916.indreb.setup.ModGeneration.setupOres

### ISSUE THREAD

**Issue by ProsperCraft** [Maciej916/Industrial-Reborn#1]
**Describe the bug**
Server crashes when starting a dedicated server.

**Versions**
- **Industrial Reborn**: Industrial-Reborn-1.15.2-0.2.1
- **Forge**: forge-1.15.2-31.1.0

Crash report - https://gist.github.com/ProsperCraft/41022d3e87c43248d44b224a7d352601

Log- https://gist.github.com/ProsperCraft/c98b36a70d9288614ec9af05ed8ffe1a

**Comment by Maciej916** [comment]
Fixed in [v0.2.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/2875416)
