### ISSUE TITLE
Industrial Craft License

### ISSUE THREAD

**Issue by NillerMedDild** [Maciej916/Industrial-Reborn#1]
Hi!

I thought I'd let you know, that IC2 is licensed All Rights Reserved. The amount of similarities Industrial Reborn has with IC2 will probably become an issue down the line.

I'm in no way affiliated with IC2, I just thought I'd give you a friendly heads up :)

**Comment by Maciej916** [comment]
Hello, I know that I only used ic2 textures as placeholder and Ill change them in next versions. Also I don't want to make copy of industrial craft I want to make my own machines ect. but it might look like that now. It will be much different when i add more content :)

**Comment by NillerMedDild** [comment]
Alright then :)
