### ISSUE TITLE
0.11.2 Errors out when loading (ie Broken version)

### ISSUE THREAD

**Issue by nekomaster** [Maciej916/Industrial-Reborn#1]
**Describe the bug**
With Industrial reborn as the only mod, Forge throws errors on bootup that stop the game from loading further.

**To Reproduce**
Steps to reproduce the behavior (for MC1.18):
1. Install forge 38.0.17
2. Put indreb-1.18-0.11.2.jar in your mod folder
3. Start Forge 1.18 from the Launcher
4. Enjoy errors.

**Expected behavior**
Game should load and get to main menu (so one can get in game and play with the mod)

**Versions**
- **Industrial Reborn**: 1.18-

0.11.2
- **Forge**: 38.0.17

[crash-2021-12-10_16.05.09-fml.txt](https://github.com/Maciej916/Industrial-Reborn/files/7695473/crash-2021-12-10_16.05.09-fml.txt)
[debug.log](https://github.com/Maciej916/Industrial-Reborn/files/7695474/debug.log)
[latest.log](https://github.com/Maciej916/Industrial-Reborn/files/7695475/latest.log)

**Comment by Maciej916** [comment]
Sorry that was a mistake, It was meant to be visible on curseforge.

**Comment by Maciej916** [comment]
Fixed version is now out [https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/3559579](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/3559579)
