### ISSUE TITLE
[1.16.x] Ore generating whilst disabled

### ISSUE THREAD

**Issue by advaluti-dev** [Maciej916/Industrial-Reborn#10]
**Describe the bug**
When disabling ore generation (enable = false for each ore, whilst keeping main generation true) in client config, ore will still generate.

**To Reproduce**
1. Disable ore generation per block 
2. Load up new world/chunks
3. See ores still generate

**Expected behavior**
Ore generation of indiv. ores to be disabled

**Versions**
- **Industrial Reborn**: 1.16.1-0.8.1
- **Forge**: 32.0.66

**Comment by Maciej916** [comment]
Should be finally fixed in 1.16.3-0.9.0.
