### ISSUE TITLE
crashing in menu from rubber tree ? 

### ISSUE THREAD

**Issue by IchigoGames** [Maciej916/Industrial-Reborn#12]
**Describe the bug**
Not sure how this is happening all i did is look up rubber in jei now im crashing in my menu not even in game i am using fancymenu

**To Reproduce**
Not sure

**Expected behavior**
Not crashing

**Versions**
- **Industrial-Reborn-1.16.3-0.9.0
- **Forge**:34.1.17

https://pastebin.com/VbS8qrGi

**Comment by Maciej916** [comment]
Fixed in [v1.16.3-0.9.1](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/3076845)
