### ISSUE TITLE
Fluid enriching recipes cause crashes with Quark Oddities

### ISSUE THREAD

**Issue by Hubry** [Maciej916/Industrial-Reborn#13]
**Describe the bug**
https://github.com/Maciej916/Industrial-Reborn/blob/f3190be3f797d2ab1cc5c0af417feafaa63deac4/src/main/java/com/maciej916/indreb/common/receipe/impl/FluidEnrichingRecipe.java#L103-L106
Minecraft marks this method as returning non-null (Mojang puts non-null annotations on practically every `package-info.java` in every package), and Quark Oddities traverses the whole recipe collection to find what uses iron for the magnet feature.
https://github.com/VazkiiMods/Quark/issues/3532

**To Reproduce**
1. Install Industrial Reborn
2. Install Quark and Quark Oddities
3. Enter a world

**Expected behavior**
Not crashing.

**Versions**
- **Industrial Reborn**: 1.18.1-0.12.4 (taken from the linked Quark issue)
- **Forge**: 1.18.1-39.0.10

**Comment by Maciej916** [comment]
Should be fixed in [0.14.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/4076608)
