### ISSUE TITLE
Recipe guide overflow (no mod)

### ISSUE THREAD

**Issue by chlwhdtn03** [Maciej916/Industrial-Reborn#15]
**Describe the bug**
GUI SCALE : 1
![2022-01-24_11 47 11](https://user-images.githubusercontent.com/20380647/150713871-50dc9a1e-d492-4835-be9a-065b22b77b3c.png) 
GUI SACLE : Auto
![2022-01-24_11 46 38](https://user-images.githubusercontent.com/20380647/150713874-d3e98d79-3f63-429b-8a8d-5cc3dcf7b8c9.png) 

We can't scrolling that recipes
If player don't use JEI or other mod, can't find item recipe (but if player have all of item that need to make a item, will appear top) 
😢 

**To Reproduce**

1. Put in IC2 Materials in your inventory (Tin, Cupper, Plate, Rubber and all importance materials) as you can
2. Open Crafting Table
2. Enable Crafting Guide (Click green book)
3. Click the **lava bucket** and **apple** on **left tab menu**
4. You can see IC2 Items recipes
5. Right Click to expand recipes
![2022-01-24_12 02 12](https://user-images.githubusercontent.com/20380647/150715198-572fd74d-f447-4ef7-945e-a3c01933e1dc.png)

**Expected behavior**
### Please separate item recipe!
I had not making mod, so I don't know how to fix it...
but i hope it will be fixed

**Versions**

- **Industrial Reborn**: 1.18.1-0.12.4
- **Forge**: 39.0.55

**Comment by samuelh2005** [comment]
Looks like a vanilla Minecraft bug because Mojang has not planed for this many recipes.

**Comment by Maciej916** [comment]
I will split the recipes into multiple groups it will help a little with that
