### ISSUE TITLE
Game crashes when i try attach a red connector from xnet

### ISSUE THREAD

**Issue by void513** [Maciej916/Industrial-Reborn#17]
**Describe the bug**
using lastest version of both mod when i attach a red connector from xnet to alloy  smelter it crash the game.Heres the crash report 
https://www.pastiebin.com/6207fd015e7b3
I will be send a report to the creaters of xnet also 

**To Reproduce**
1.
2.
3.

**Expected behavior**

**Versions**
- **Industrial Reborn**: 1.18.1-0.12.4
- **Forge**: 39.0.64

**Comment by Maciej916** [comment]
This will be fixed in next update

**Comment by Maciej916** [comment]
Should be fixed in [0.14.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/4076608)
