### ISSUE TITLE
Artifact while viewing gui of MFE in 1.17.1

### ISSUE THREAD

**Issue by kreezxil** [Maciej916/Industrial-Reborn#19]
**Describe the bug**
While looking at the gui for the MFE in 1.17.1

**Screenshot**
![image](https://user-images.githubusercontent.com/3880072/155361104-2c4fe7dc-0f44-4252-943b-3eb57fe5b6e4.png)

**Versions**
- **Industrial Reborn**: 1.17.1-0.10.1
- **Forge**: 1.17.1-37.1.1

**Comment by Maciej916** [comment]
This will be fixed in next update

**Comment by Maciej916** [comment]
Should be fixed in [0.14.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/4076608)
