### ISSUE TITLE
Ejector Upgrade Exports Ingredients Instead Of Result

### ISSUE THREAD

**Issue by Mrbt0907** [Maciej916/Industrial-Reborn#21]
**Describe the bug**
The ejector upgrade doesn't export finished results. It instead ejects ingredients. Along side this, any attempts to pull  the product through pipes from other mods also only grabs the ingredients instead.

**To Reproduce**
1. Craft a crusher, electric furnace, or any machine that accepts the ejector upgrade
2. Craft the ejector upgrade or any means to pull the output out
3. Place the machine and install the ejector upgrade with a chest nearby
4. Place an ingredient like iron ore into the machine
5. Instead of the result being ejected, the iron ore should be ejected

**Expected behavior**
The ejector upgrade should only push out the result instead of the ingredients. Also, external mods like pipes should be able to pull out the result also.

**Versions**
- **Industrial Reborn**: 0.12.4
- **Forge**: 1.18.1

**Comment by Mrbt0907** [comment]
Upon further investigation, I can only export the result from the bottom, which should not be the case.

**Comment by Maciej916** [comment]
This should be fixed in the latest version for 1.19.2

**Comment by Mrbt0907** [comment]
Thank you
