### ISSUE TITLE
Crashing with IC2 Classic

### ISSUE THREAD

**Issue by Christofmeg** [Maciej916/Industrial-Reborn#25]
**Describe the bug**
Latest version of mod caught exception during event FMLCommonSetupEvent

**To Reproduce**
1. Install the following:
- Forge 1.19.2 - 43.1.47
- indreb-1.19.2-0.14.0
- IC2Classic-1.19.2-2.0.0

**Expected behavior**
Not crash?

https://hastebin.com/mijebixilo.sql

**Comment by Speiger** [comment]
Info from my side.
Basically the Irrigation Terraformer Blue Print tries to map logs to leaves that way a tree can be properly constructed.
Issue is RNG isn't really viable with that, so I am throwing in a null to get a default state.

**Comment by Maciej916** [comment]
Thank you for the information. I will just add check if RandomSource is null and it should fix the crash issue.

**Comment by Maciej916** [comment]
Fixed in [0.14.1](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/4064540)

**Comment by Speiger** [comment]
Ty for the understanding ^^
