### ISSUE TITLE
Config for disabling Bronze and Bronze tools

### ISSUE THREAD

**Issue by ghost** [Maciej916/Industrial-Reborn#27]
## What should be added or changed?

Add config option like it was back in IC2 where you could disable crafting of bronze, bronze dust and even bronze tools (even shield)

## Why should this be done?

It would be huge improvement for pack makers like myself and I would not need other mod for that

**Comment by Maciej916** [comment]
There is currently no option for that but i think it is easy to disable recipe via datapacks.
