### ISSUE TITLE
Multiplayer - Unable to host [1.19.2-0.14.1]

### ISSUE THREAD

**Issue by Nydekore99** [Maciej916/Industrial-Reborn#28]
**Describe the bug**
Industrial Reborn unable to be hosted on Multiplayer servers

**To Reproduce**
Seemingly just hosting on Apex Server Hosting. The issue was isolated down to just this particular mod.

**Expected behavior**
I was hoping to host a modpack featuring this mod using Apex Server Hosting. I have not tried any other host but I doubt Apex is at fault here. As said above, this issue was isolated down to just Industrial Reborn.

**Versions**
- **Industrial Reborn**: 1.19.2-0.14.1
- **Forge**: 1.19.2-forge-43.1.34

[crash-2022-11-08_03.18.25-fml.txt](https://github.com/Maciej916/Industrial-Reborn/files/9957342/crash-2022-11-08_03.18.25-fml.txt)

**Comment by Nydekore99** [comment]
Should also be mentioned, this combination of mods works as expected in single player.

**Comment by Maciej916** [comment]
This will be fixed in next update

**Comment by Maciej916** [comment]
Should be fixed in [0.14.2](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/4076608)
