### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by congueror** [Maciej916/Industrial-Reborn#5]
## What should be added or changed?

- Make your mod open source.

## Why should this be done?

- So people new to modding can look at your code and get examples and such.

**Comment by Maciej916** [comment]
I'm also new to moding, Im basicly learning how to program in Java by creating mods. I think im not the person you want to learn from, I recommend you to watch McJty tutiorials (https://youtu.be/gbhfKgAAmMM) I learned alot from his videos. Also this mod was created closed source and I don't plan to change it.

**Comment by congueror** [comment]
ok, thanks for the link :)
