### ISSUE TITLE
Compatibility with other mods

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Maciej916/Industrial-Reborn#7]
Add compatibility for [Industrial Reborn](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn) for Minecraft 1.16.1 to use [SurvivalPlus](https://www.curseforge.com/minecraft/mc-mods/survivalplus) and [SimpleOres](https://www.curseforge.com/minecraft/mc-mods/simpleores) items for crafting of your machines and cables. 

Your crusher does nicely grind the other mods' ores.

**Comment by Maciej916** [comment]
Yes I'll update recipes to accept other mods ores and items.
