### ISSUE TITLE
Rubber Wood

### ISSUE THREAD

**Issue by whatthedrunk** [Maciej916/Industrial-Reborn#9]
Rubber wood cannot to used to make items such as chests. It also cannot be used as fuel.

ATM6 Pack
Industrial-Reborn-1.16.1-0.7.1.jar
Forge 31.2.31

**Comment by Maciej916** [comment]
Fixed in [v0.8.0](https://www.curseforge.com/minecraft/mc-mods/industrial-reborn/files/3001999)
